=== LeonardoDonici/Projects/Site web 1/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana)+>
<!ELEMENT persoana (nume,prenume,varsta,adresa,PhoneNumber,studii,WorkExperience)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT PhoneNumber (#PCDATA)>
<!ELEMENT studii (Liceu,Facultate)>
<!ELEMENT Liceu (#PCDATA)>
<!ELEMENT Facultate (#PCDATA)>
<!ELEMENT WorkExperience (#PCDATA)>

=== LeonardoDonici/Projects/Site web 1/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Stefan cel Mare</strada>
            <numar>17</numar>
            <localitate>Draganesti</localitate>
            <judet>Galati</judet>
            <tara>Romania</tara>
        </adresa>

        <PhoneNumber>0725502945</PhoneNumber>
        <studii>
            <Liceu>Colegiul National Calistrat Hogas</Liceu>
            <Facultate>Facultatea de Constructii</Facultate>
        </studii>
        <WorkExperience>
            Continental Summer Practice,  
            Vitesco Internship
        </WorkExperience>

    </persoana>
    <persoana id="2">
        <nume>Popa</nume>
        <prenume>Ionescu</prenume>
        <varsta>28</varsta>
        <adresa>
        <strada>Florin Petrescu</strada>
        <numar>12</numar>
        <localitate>Papucesti</localitate>
        <judet>Braila</judet>
        <tara>Romania</tara>
        </adresa>

        <PhoneNumber>0726602245</PhoneNumber>
        <studii>
            <Liceu>Colegiul National Calistrat Hogas</Liceu>
            <Facultate>Facultatea de Constructii</Facultate>
        </studii>
        <WorkExperience>
            Continental Summer Practice, 
            Amazon Internship
        </WorkExperience>
    </persoana>

    <persoana id="3">
        <nume>Minculescu</nume>
        <prenume>Andrei</prenume>
        <varsta>21</varsta>
        <adresa>
        <strada>Anton Pan</strada>
        <numar>12</numar>
        <localitate>Papucesti</localitate>
        <judet>Braila</judet>
        <tara>Romania</tara>
        </adresa>

        <PhoneNumber>0725502945</PhoneNumber>
        <studii>
            <Liceu>Colegiul National Calistrat Hogas</Liceu>
            <Facultate>Facultatea de Constructii</Facultate>
        </studii>
        <WorkExperience>
            Amazon Summer Practice,   
            Bitdefender Internship
        </WorkExperience>
        
    </persoana>
</persoane>
